apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xyliganimbot-data-pvc
  namespace: xyliganimbot
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      usage: data  # Ищем PV с меткой usage: data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xyliganimbot-logs-pvc
  namespace: xyliganimbot
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      usage: logs  # Ищем PV с меткой usage: logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xyliganimbot-models-pvc
  namespace: xyliganimbot
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      usage: models  # Ищем PV с меткой usage: models
